---
  - name: apt-get install mysql
    apt:
      name: "{{ item }}"
    become: yes 
    with_items:
    - python-mysqldb
    - mysql-client
    - mysql-server

  - name: create user to install db
    mysql_user:
      name: "colte_db"
      password: "colte_db"
      host: localhost
      priv: 'colte_db.*:ALL'
    become: yes

  - name: test for database existence
    mysql_db:
      login_user: "colte_db"
      login_password: "colte_db"
      name: colte_db
      state: present
    register: dbstatus

  - name: install default database
    mysql_db:
      login_user: "colte_db"
      login_password: "colte_db"
      name: colte_db
      state: import
      target: "{{ epc_dir }}/spencer_configs/bokondini.sql"
    when: dbstatus.changed == True #this means that we just created colte_db and should populate it
