---
### STEP ONE: DOWNLOAD/INSTALL DOCKER IMAGES AND START THEM    
    - name: fetch docker images
      docker_image:
        name: "{{ item }}"
      with_items:
      - mongo:3.0
      - rocket.chat
      become: yes

# docker run --name db -d mongo:3.0 --smallfiles
    - name: create mongodb docker container
      docker_container:
        name: db
        image: mongo:3.0
        command: --smallfiles
        restart_policy: always
        state: present
      become: yes

# docker run --name rocketchat -p 9081:3000 --env ROOT_URL=http://localhost --link db -d rocket.chat
    - name: create rocketchat docker container
      docker_container:
        name: rocketchat
        image: rocket.chat
        ports: 9081:3000
        links: db
        env:
            ROOT_URL: http://localhost:9081
            Show_Setup_Wizard: completed
        restart_policy: always
        state: present
      become: yes

### STEP TWO: SYMLINK NGINX INTO SITES-ENABLED
    - name: link website configuration file
      copy:
        src: "/etc/nginx/sites-enabled/rocketchat.conf"
        dest: "/etc/nginx/sites-available/rocketchat.conf"
        state: link
      become: yes
