---

  - name: apt-get virtualbox and vagrant
    apt:
      update_cache: yes
      name: "{{ item }}"
    become: yes
    with_items:
    - virtualbox
    - vagrant
    when: distro == 'bionic'

##### DEBIAN (STRETCH) NEEDS TO ADD CUSTOM REPO TO GET VBOX VERSION 5.1 EXACTLY
  - name: add virtualbox repo
    lineinfile:
      dest: /etc/apt/sources.list.d/virtualbox.list
      line: "deb http://download.virtualbox.org/virtualbox/debian stretch contrib"
      create: yes
    become: yes
    when: distro == 'stretch'

  - name: add oracle vbox key to apt
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present
    become: yes
    when: distro == 'stretch'

  - name: apt-get virtualbox and vagrant
    apt:
      update_cache: yes
      name: "{{ item }}"
    become: yes
    with_items:
    - virtualbox-5.1
    - vagrant
    when: distro == 'stretch'
