---
  - name: check for environment vars
    fail: msg= "Killing ansible script, environment variables not set! COLTE_DIR = {{ ansible_env.COLTE_DIR }}"
    when: colte_dir is not defined

  - name: check for distro sanity
    fail:
    when: distro != 'bionic' and distro != 'stretch'

  - name: set colte_dir
    set_fact:
      colte_dir: "{{ role_path/../../../..}}"

  - name: apt-get update
    apt:
      update_cache: yes
      cache_valid_time: 3600
    become: yes