---
  - name: set common vars colte_dir and distro
    set_fact:
      colte_dir: "{{ role_path/../../../..}}"
      distro: "{{ ansible_distribution_release }}" # VALID OPTIONS: "bionic" or "stretch"

  - name: echo colte_dir
    shell: "echo {{ colte_dir }}"

  - name: check for distro sanity
    fail:
    when: distro != 'bionic' and distro != 'stretch'

  - name: apt-get update
    apt:
      update_cache: yes
      cache_valid_time: 3600
    become: yes