# OSM is OpenStreetMaps
---
  - name: check if osm.box exists
    stat: 
      path: "{{ item.path }}"
    register: osm_box
    with_items:
    - {path: "/usr/local/etc/colte/boxes/osm.box"}

  - fail: msg="OSM box doesn't exist. Download from colte.cs.washington.edu/boxes/osm.box"
    when: osm_box.stat.exists == False

  - name: import the OSM server Vagrant box
    shell: vagrant box add osm.box --name osm
    args:
      chdir: "{{ osm_dir }}"
    ignore_errors: yes

  - name: symlink rails app log into /var/log/colte
    file:
      src: "{{ osm_dir }}/osm_rails.log"
      dest: "/var/log/colte/osm_rails.log"
      state: link
    become: yes

# STEP 2: install/configure the tile server
  - name: download docker tile-server image
    docker_image:
      name: klokantech/openmaptiles-server
    become: yes

  - name: configure the OSM tile server image (Docker)
    docker_container:
      name: osm_tileserver
      image: klokantech/openmaptiles-server
      ports: 9085:80
      volumes: "/usr/local/etc/colte/osm_tiles:/data"
      restart_policy: always
      state: present
    become: yes
#docker run --rm -it -v $(pwd):/data -p 9085:80 klokantech/openmaptiles-server

  - name: copy website configuration file
    copy:
      src: "{{ osm_dir }}/osm.conf"
      dest: "/etc/nginx/sites-available/osm.conf"
      force: no
    become: yes
