---
- hosts: localhost

  roles:
# you can build any of our debs from scratch if you choose (not needed)
#    - { role: build_libraries}
#    - { role: build_epc}
#    - { role: build_media}

# core LTE network code
    - { role: epc}
    - { role: billing}
    - { role: webgui}

# optional/additional webservices
    - { role: media}
    - { role: wiki}
    - { role: chat}

# ALWAYS run configure at the end
    - { role: configure}

# (currently disabled/broken)
#    - { role: emergency}
#    - { role: zotac}
#    - { role: maps}
