---
  - name: ensure log directory exists
    file:
      path: /var/log/colte
      state: directory
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0755
    become: yes

  - name: ensure config directory exists
    file:
      path: /usr/local/etc/colte
      state: directory
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0755
    become: yes

  - name: symlink oai epc config files
    file:
      src: /usr/local/etc/oai
      dest: /usr/local/etc/colte/oai
      state: link
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0755
    become: yes
