---      
### STEP ONE: DOWNLOAD/INSTALL/START DOCKER IMAGES
  - name: fetch docker images
    docker_image:
      name: "{{ item }}"
    with_items:
    - quantumobject/docker-xowa
    become: yes

  - name: configure xowa docker container
    docker_container:
      name: xowa
      image: quantumobject/docker-xowa
      ports: 9082:8080
      volumes: "{{ system_dir }}/wiki:/opt/xowa/wiki"
      # detach: true
      restart_policy: always
      state: started
    become: yes
# command: -v yours/storage:/opt/xowa/wiki
# note: -v yours/storage:/opt/xowa/wiki ==> to add,and/or to keep the differents wikipedia after upgrading , replacing your container.

### STEP TWO: SYMLINK NGINX INTO SITES-ENABLED
  - name: link website configuration file
    file:
      src: "/etc/nginx/sites-available/xowa.conf"
      dest: "/etc/nginx/sites-enabled/xowa.conf"
      state: link
    become: yes

### STEP THREE: WRITE DOWN THAT WE'VE INSTALLED WIKI
  - name: write to installed_services.txt
    lineinfile:
      dest: "/usr/local/etc/colte/installed_services.txt"
      regexp: "wiki:"
      line: "wiki: 1"
    become: yes







  # SMS BIG NOTE: CHANGE THESE DOWNLOAD SCRIPTS INTO SOME SEPARATE FILE
  # - name: make storage directory
  #   file:
  #     path: "{{ system_dir }}/wiki/{{ item }}"
  #     state: directory
  #     recurse: yes
  #   with_items:
  #   - temp
  #   - simple.wikipedia.org

  # - name: must increase sudo timeout for this script to run successfully
  #   lineinfile:
  #     path: /etc/sudoers
  #     regexp: 'env_reset'
  #     line: 'Defaults env_reset, timestamp_timeout=60'
  #     owner: root
  #     group: root
  #     mode: 440
  #   become: yes

  # - name: download simple wikipedia (html/text)
  #   get_url:
  #     url: http://archive.org/download/Xowa_simplewiki_latest/{{ item }}
  #     dest: "{{ emergency_dir }}/xowa_storage/temp"
  #   with_items:
  #   - Xowa_simplewiki_2017-05_core.zip
  #   - Xowa_simplewiki_2017-05_xtn.search.core.zip
  #   - Xowa_simplewiki_2017-05_xtn.search.link_title_ns.000_db.001.zip
  #   - Xowa_simplewiki_2017-05_xtn.search.link_title_ns.999_db.001.zip
  #   - Xowa_simplewiki_2017-05_html_ns.000.zip
  #   - Xowa_simplewiki_2017-05_html_ns.004.zip
  #   - Xowa_simplewiki_2017-05_html_ns.014.zip
  #   - Xowa_simplewiki_2017-05_html_ns.008.zip
  #   - Xowa_simplewiki_2017-05_xtn.category.core.zip
  #   - Xowa_simplewiki_2017-05_xtn.category.link_db.001.zip
  #   - Xowa_simplewiki_2017-05_xtn.fulltext_search.001.zip

  # - name: download simple wikipedia (images)
  #   get_url:
  #     url: http://archive.org/download/Xowa_simplewiki_latest/{{ item }}
  #     dest: "{{ emergency_dir }}/xowa_storage/temp"
  #   with_items:
  #   - Xowa_simplewiki_2017-05_file_core.zip
  #   - Xowa_simplewiki_2017-05_file_ns.000_db.001.zip
  #   - Xowa_simplewiki_2017-05_file_ns.000_db.002.zip
  #   - Xowa_simplewiki_2017-05_file_ns.004_db.001.zip
  #   - Xowa_simplewiki_2017-05_file_ns.014_db.001.zip

  # - name: unzip and load simple wikipedia
  #   unarchive:
  #     src: "{{ emergency_dir }}/xowa_storage/temp/{{ item }}"
  #     dest: "{{ emergency_dir }}/xowa_storage/simple.wikipedia.org/"
  #   with_items:
  #   - Xowa_simplewiki_2017-05_core.zip
  #   - Xowa_simplewiki_2017-05_xtn.search.core.zip
  #   - Xowa_simplewiki_2017-05_xtn.search.link_title_ns.000_db.001.zip
  #   - Xowa_simplewiki_2017-05_xtn.search.link_title_ns.999_db.001.zip
  #   - Xowa_simplewiki_2017-05_html_ns.000.zip
  #   - Xowa_simplewiki_2017-05_html_ns.004.zip
  #   - Xowa_simplewiki_2017-05_html_ns.014.zip
  #   - Xowa_simplewiki_2017-05_html_ns.008.zip
  #   - Xowa_simplewiki_2017-05_xtn.category.core.zip
  #   - Xowa_simplewiki_2017-05_xtn.category.link_db.001.zip
  #   - Xowa_simplewiki_2017-05_xtn.fulltext_search.001.zip
  #   - Xowa_simplewiki_2017-05_file_core.zip
  #   - Xowa_simplewiki_2017-05_file_ns.000_db.001.zip
  #   - Xowa_simplewiki_2017-05_file_ns.000_db.002.zip
  #   - Xowa_simplewiki_2017-05_file_ns.004_db.001.zip
  #   - Xowa_simplewiki_2017-05_file_ns.014_db.001.zip

  # - name: cleanup temp folder
  #   file: path='{{ emergency_dir }}/xowa_storage/temp' state=absent
