---
  - name: apt-get install ums
    apt:
      name: colte-ums
    become: yes

#### SYMLINK THE FILES DIRECTORY INTO COLTE
  - name: symlink website into sites-enabled
    file:
      src: "/etc/ums/files"
      dest: "/usr/local/etc/colte/media" # link
      state: link

  - name: write information to ums.conf (used for nginx)
    lineinfile:
      dest: "{{ ums_dir }}/ums.conf"
      regexp: "{{ item.field }}"
      line: "{{ item.line }}"
    with_items:
    - {field: "server_name", line: "  server_name media.{{ network_name }};"}
    
  - name: copy website configuration file
    copy:
      src: "{{ ums_dir }}/ums.conf"
      dest: "/etc/nginx/sites-available/ums"
    become: yes

  - name: symlink website into sites-enabled
    file:
      src: "/etc/nginx/sites-available/ums"
      dest: "/etc/nginx/sites-enabled/ums"
      state: link
    become: yes

  - name: add localhost dns pointers in /etc/hosts 
    lineinfile:
      dest: "/etc/hosts"
      regexp: "media"
      line: "127.0.0.1 media.{{ network_name }}"
    become: yes

  - name: restart nginx
    service: name=nginx state=reloaded
    become: yes
