---
  - name: apt-get install ums
    apt:
      name: colte-ums
    become: yes
    when: build_media == '0'

  - name: install UMS from built .deb
    apt: 
      deb: "{{ package_dir }}/extras/ums.deb"
    become: yes
    when: build_media == '1'

  - name: symlink ums files directory into /usr/local/etc/colte
    file:
      src: "/etc/ums/files"
      dest: "/usr/local/etc/colte/media"
      state: link

  - name: copy website configuration file
    copy:
      src: "{{ extras_dir }}/ums.conf"
      dest: "/etc/nginx/sites-available/ums.conf"
      force: no
    become: yes