---
####### Ubuntu can just apt-get npm, Debian has to use curl script to fetch it ########
  - name: install node and npm
    apt:
      name: "{{ item }}"
    with_items:
    - npm
    become: yes
    when: distro == 'bionic'

  - name: ensure nodejs not already installed (stretch)
    apt:
      name: nodejs
      state: absent
    become: yes
    when: distro == 'stretch'

  - name: manually download npm (stretch)
    get_url:
      url: https://deb.nodesource.com/setup_6.x
      dest: /tmp/npm_setup.sh
      mode: 0755
    when: distro == 'stretch'

  - name: manually install npm (stretch)
    shell: bash /tmp/npm_setup.sh
    become: yes
    when: distro == 'stretch'

  - name: install node and npm
    apt:
      name: "{{ item }}"
    with_items:
    - nodejs
    become: yes    
    
  - name: npm install dependencies
    npm:
      path: "{{ webgui_dir }}"

  - name: make /usr/bin/webgui directory
    file:
      path: "{{ package_dir }}/webgui/usr/bin/"
      state: directory

  - name: copy production.env file to .env
    copy: 
      src: "{{ webgui_dir }}/production.env"
      dest: "{{ webgui_dir }}/.env"
      force: yes

  - name: copy webgui files to package
    synchronize: 
      src: "{{ webgui_dir }}/"
      dest: "{{ package_dir }}/webgui/usr/bin/colte-webgui"

  - name: remove unneeded files from package
    file:
      path: "{{ package_dir }}/webgui/usr/bin/colte-webgui/{{ item }}"
      state: absent
    with_items:
    - "production.env"
    - "local_dev.env"
    - "README.md"

  - name: create .deb file
    shell: dpkg-deb --build webgui colte-webgui_{{ webgui_version }}{{ distro }}_amd64.deb
    args:
      chdir: "{{ package_dir }}"

  - name: set build_webgui variable
    set_fact:
      build_webgui: "1"
