---
  - name: stop apache2 sevice if running (IMPORTANT before installing nginx)
    service:
      name: apache2
      state: stopped
      enabled: no
    become: yes
    ignore_errors: yes # needed because command will fail if apache2 is not installed

  - name: apt-get nginx
    apt:
      name: "{{ item }}"
    become: yes
    with_items:
    - nginx

  - name: remove default nginx website (or server will not launch)
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    become: yes

  - name: restart nginx
    service: name=nginx state=reloaded
    become: yes

