---
  - name: disable network manager
    systemd:
      name: network-manager
      enabled: no

  - name: enable systemd-networkd
    systemd:
      name: systemd-networkd
      enabled: yes
      state: started

  - name: configure journald for large amounts of persistent storage
    lineinfile:
      dest: "/etc/systemd/journald.conf"
      regexp: "{{ item.field }}"
      line: "{{ item.line }}"
    with_items:
    - {field: "Storage=", line: "Storage=persistent"}
    - {field: "SystemMaxUse=", line: "SystemMaxUse=20GB"}
    - {field: "SystemMaxFileSize=", line: "SystemMaxFileSize=10GB"}

# systemctl restart systemd-journald
  - name: restart systemd-journald
    systemd:
      state: restarted
      name: systemd-journald
    become: yes

  # - name: systemd enable epc
  #   systemd:
  #     name: epc
  #     enabled: yes
  #   become: yes