---
####### Ubuntu can just apt-get npm, Debian has to use curl script to fetch it ########
  - name: install node and npm
    apt:
      name: "{{ item }}"
    with_items:
    - npm
    become: yes
    when: distro == 'bionic'

  - name: download script to install npm
    get_url:
      url: https://deb.nodesource.com/setup_6.x
      dest: /tmp/npm_setup.sh
      mode: 0755
    when: distro == 'stretch'

  - name: run script to install npm
    shell: bash /tmp/npm_setup.sh
    become: yes
    when: distro == 'stretch'

  - name: install node and npm
    apt:
      name: "{{ item }}"
    with_items:
    - nodejs
    become: yes    
    
  - name: npm install dependencies
    npm:
      path: "{{ webgui_dir }}"

  - name: copy production.env file to .env
    copy: 
      src: "{{ webgui_dir }}/production.env"
      dest: "{{ webgui_dir }}/.env"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      mode: 0755
      force: no

  - name: copy website configuration file
    copy:
      src: "{{ webgui_dir }}/install_scripts/webgui.conf"
      dest: "/etc/nginx/sites-available/webgui.conf"
      force: no
    become: yes

  - name: dynamically write colte_webgui.service
    lineinfile:
      dest: "{{ webgui_dir }}/install_scripts/colte_webgui.service"
      regexp: "{{ item.field }}"
      line: "{{ item.line }}"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
    with_items:
    - {field: "ExecStart", line: "ExecStart=/bin/bash -c \"{{ webgui_dir }}/bin/www >> /var/log/colte/webgui.log 2>&1\""}
    - {field: "User", line: "User={{ ansible_user_id }}"}
    - {field: "Group", line: "Group={{ ansible_user_id }}"}
    - {field: "WorkingDirectory", line: "WorkingDirectory={{ webgui_dir }}"}

  - name: copy webgui.service to /etc/systemd/system
    copy: 
      src: "{{ webgui_dir }}/install_scripts/colte_webgui.service"
      dest: "/etc/systemd/system/colte_webgui.service"
      mode: 0644
      force: no
    become: yes


