---
### Switch on build_epc TO DETERMINE WHETHER WE INSTALL FROM APT-GET OR THE LOCALLY BUILT .DEB FILES
  - name: apt-get install CoLTE WebGUI
    apt:
      name: colte-webgui
    become: yes
    when: build_webgui is not defined

  - name: install EPC from built .debs
    apt: 
      deb: "{{ package_dir }}/extras/webgui.deb"
    become: yes
    when: build_webgui is defined
### end switch
