#### SMS TODO: PACKAGE UP INTO .DEB FILES

---
  - name: apt-get update
    apt:
      update_cache: yes
      cache_valid_time: 3600
    become: yes

  - name: apt-get install build dependencies
    apt:
      name: "{{ item }}"
    with_items:
# HSS
    - autoconf
    - automake
    - bison
    - build-essential
    - cmake
    - cmake-curses-gui
    - doxygen
    - doxygen-gui
    - flex
#    - gdb
    - pkg-config
    - git
#    - subversion
    - libconfig-dev
    - libgcrypt11-dev
    - libidn2-0-dev
    - libidn11-dev
#    - default-libmysqlclient-dev
    - libpthread-stubs0-dev
    - libsctp1
    - libsctp-dev
    - libssl-dev
    - libtool
    - openssl
    - nettle-dev
    - nettle-bin
    - php
    - python-pexpect
# MME
    - castxml
    - guile-2.0-dev
    - libgmp-dev
    - libhogweed?
    - libgtk-3-dev
    - libxml2
    - libxml2-dev
    - mscgen
    - check
    - python
    - libgnutls28-dev
#    - ethtool
#    - iproute2
#    - vlan
#    - tshark
    - python-dev
    - unzip
# THIS IS FOR FREEDIAMETER
    - debhelper
    - g++
    - gcc
    - libpq-dev
    - mercurial
    - ssl-cert
    - swig      
# THIS IS FOR LIBGTPNL
    - libmnl-dev
    become: yes

############### FREEDIAMETER INSTALLATION ###################
  - name: freeDiameter - clone from my github copy
    git:
      repo: https://github.com/spencersevilla/freediameter.git
      dest: "/tmp/freediameter"

  - name: freeDiameter - create build directory
    file:
      path: "/tmp/freediameter/build"
      state: directory
      mode: 0755

  - name: freeDiameter - cmake prep
    shell: |
      cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DDISABLE_PEER_EXPIRY:BOOL=ON ../
    args:
      chdir: "/tmp/freediameter/build"

  - name: freeDiameter - build
    make:
      chdir: "/tmp/freediameter/build"

  - name: freeDiameter - install
    make:
      chdir: "/tmp/freediameter/build"
      target: install
    become: yes

########## PATCHED ASN1C INSTALLATION #################
  - name: asn1c - fetch rev 1516 patched from my github copy
    git:
      repo: https://github.com/spencersevilla/asn1c.git
      dest: "/tmp/asn1c"
      force: yes

  - name: asn1c - configure
    shell: |
      ./configure
    args:
      chdir: "/tmp/asn1c"

  - name: asn1c - build
    make:
      chdir: "/tmp/asn1c"

  - name: asn1c - install
    make:
      chdir: "/tmp/asn1c"
      target: install
    become: yes

############ LIBGTPNL ######################
  - name: libgtpnl - clone from osmocom git
    git:
      repo: git://git.osmocom.org/libgtpnl
      dest: "/tmp/libgtpnl"
      force: yes

#    git reset --hard 345d687
#    NOTE: could also just do "git checkout 345d687"
#    patch --verbose -p1  < $OPENAIRCN_DIR/build/tools/libgtpnl.LTE_dedicated_bearer.v0.patch 
# NOTE: if this causes build failure, comment out become and just add sudo
  - name: libgtpnl - configure
    shell: |
      git reset --hard 345d687
      patch --verbose -p1  < {{ epc_dir }}/build/tools/libgtpnl.LTE_dedicated_bearer.v0.patch 
      autoreconf -fi
      ./configure
    args:
      chdir: "/tmp/libgtpnl"

  - name: libgtpnl - build
    make:
      chdir: "/tmp/libgtpnl"

  - name: libgtpnl - install
    make:
      chdir: "/tmp/libgtpnl"
      target: install
    become: yes

  - name: libgtpnl - doing something?!?
    shell: |
      ldconfig
    args:
      chdir: "/tmp/libgtpnl"
    become: yes

############ LIB LFDS #################
  - name: liblfds - clone friom github
    git:
      repo: https://github.com/liblfds/liblfds.git
      dest: "/tmp/liblfds"

  - name: liblfds - build SHELL SCRIPT
    shell: |
      make so_dbg
      sudo rm -f /usr/local/lib/liblfds710.so
      sudo make so_install
    args:
      chdir: "/tmp/liblfds/liblfds/liblfds7.1.0/liblfds710/build/gcc_gnumake"

############ PACKAGE INTO DEBS #################
  - name: create .deb files
    shell: |
      dpkg-deb --build freediameter
      dpkg-deb --build asn1c
      dpkg-deb --build libgtpnl
      dpkg-deb --build liblfds
    args:
      chdir: "{{ package_dir }}"