---
  - name: apt-get bind
    apt:
      name: "{{ item }}"
    become: yes
    with_items:
    - bind9
    - bind9utils
    - bind9-doc

  - name: ensure /etc/bind/zones directory exists
    file:
      path: /etc/bind/zones
      state: directory
    become: yes

  - name: copy bind configuration files
    copy: 
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
      mode: 0644
      force: no
    become: yes
    with_items:
    - {src: "{{ extras_dir }}/named.conf.local", dst: "/etc/bind/named.conf.local"}
    - {src: "{{ extras_dir }}/named.conf.options", dst: "/etc/bind/named.conf.options"}
    - {src: "{{ extras_dir }}/bind_db", dst: "/etc/bind/zones/bind_db"}

  - name: restart bind9
    systemd: name=bind9 state=reloaded
    become: yes
