# Rocketchat is a free/opensource/docker-ized version of slack
---
    # - name: check for environment vars
    #   fail: msg= "Killing ansible script, environment variables not set! COLTENV = {{ ansible_env.COLTENV }}"
    #   when: coltenv is not defined
    
    - name: fetch docker images
      docker_image:
        name: "{{ item }}"
      with_items:
      - mongo:3.0
      - rocket.chat
      become: yes

    - name: copy website configuration file
      copy:
        src: "{{ extras_dir }}/rocketchat.conf"
        dest: "/etc/nginx/sites-available/rocketchat.conf"
        force: no
      become: yes

# docker run --name db -d mongo:3.0 --smallfiles
    - name: create mongodb docker container
      docker_container:
        name: db
        image: mongo:3.0
        command: --smallfiles
        restart_policy: always
        state: present
      become: yes

# docker run --name rocketchat -p 9081:3000 --env ROOT_URL=http://localhost --link db -d rocket.chat
    - name: create rocketchat docker container
      docker_container:
        name: rocketchat
        image: rocket.chat
        ports: 9081:3000
        links: db
        env:
            ROOT_URL: http://localhost:9081
            Show_Setup_Wizard: completed
        restart_policy: always
        state: present
      become: yes


